#!/bin/sh -l
#SBATCH --partition=Orion
#SBATCH -J Sp-HOF-5a_UMA
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=16
#SBATCH --mem=96G     
#SBATCH --time=120:00:00
#SBATCH --hint=nomultithread

# stop hidden threading in each worker (NumPy/MKL/OpenBLAS/etc.)
export OMP_NUM_THREADS=1
export MKL_NUM_THREADS=1
export OPENBLAS_NUM_THREADS=1
export NUMEXPR_NUM_THREADS=1
export BLIS_NUM_THREADS=1
export VECLIB_MAXIMUM_THREADS=1
export TBB_NUM_THREADS=1
export MKL_DYNAMIC=FALSE
export OPENBLAS_MAIN_FREE=1

# Print the hostname of the node executing this job
echo "Running on node: $(hostname)"
NCPU=$SLURM_CPUS_PER_TASK
srun python 5-updated-bt.py -a DFS -p 32 --mlp "UMA" -n ${NCPU} -g 2500 -c ${SLURM_JOB_NAME} > log-${SLURM_JOB_NAME}

